apiVersion: v1
kind: Pod
metadata:
  name: user-ms-pod
  labels:
    app: user-ms-pod
spec:
  containers:
  - name: user-microservice
    image: alexislagos/user-ms:v1.0
    ports:
    - containerPort: 8080  # Puerto que expone la aplicación dentro del contenedor
    env:
    - name: APPCONF_ConnectionStrings__Default
      value: server=172.21.0.2;uid=root;pwd=Colombia$2024;database=pica_challenges
---
apiVersion: v1
kind: Service
metadata:
  name: user-ms-service
spec:
  selector:
    app: user-ms-pod
  ports:
  - protocol: TCP
    port: 8080    # Puerto en localhost
    targetPort: 8080  # Puerto en el pod
  type: ClusterIP  # Tipo de servicio
